version: 2
jobs:
  build:
    docker:
      - image: paperbenni/heroku
    steps:
      - run:
          name: heroku
          command: bash start.sh
workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build
